'use strict';

// ===========================================================================
// TASK-101 — e2e "cucumber" scenarios (Given/When/Then), implemented as plain
// `node --test` cases. NO `cucumber` npm package is installed or required; these
// are scenario-style node:test cases in Given/When/Then form.
//
// Feature: the Tasks board renders its lanes DYNAMICALLY from
// tasks/team-config.json (the six hardcoded .tasks-lane divs are gone from
// renderer/index.html). Each scenario drives the REAL shipped renderer functions
//   renderTasksBoard(tab)   — builds lanes + routes cards, config-aware
//   pollTasksOnce(tab)      — reads team-config.json with keep-last-good semantics
// via test/helpers/task-101-lane-harness.js, which brace-extracts the real
// renderer/renderer.js declarations and runs them against a minimal in-memory mock
// DOM + a stubbed window.api.fs.
//
// EVERY database / filesystem / Electron call is MOCKED — window.api.fs is an
// in-memory stub, the DOM is a plain object tree; NO real DB / disk / network is
// touched. The board is driven end to end exactly as the app would drive it.
// ===========================================================================

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const H = require('./helpers/task-101-lane-harness');

const {
  loadLaneModule, makeWindow, makeDocument, makeTab, ticketsMap,
  laneEls, laneStatuses, findByClass, findAllByClass, fire,
} = H;

const CSS = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'styles.css'), 'utf8');
const HTML = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'index.html'), 'utf8');

// Fresh module + tab per scenario so the module-level drag state never leaks.
function fresh(opts) {
  const { window } = makeWindow();
  const mod = loadLaneModule(window, makeDocument(), console);
  return { mod, window, tab: makeTab(opts) };
}
// The lane element for a given data-status, or undefined.
function lane(tab, status) {
  return laneEls(tab).find((el) => el.dataset.status === status);
}
function cardStatuses(laneEl) {
  return findAllByClass(laneEl, 'task-card').map((c) => c.dataset.status);
}

// ===========================================================================
// Scenario: No config renders today's board (edge / REGRESSION)
//   Given tasks/team-config.json does not exist
//   Then five lanes render with today's order, labels and no badges
// ===========================================================================
test('Scenario: no config renders today\'s five lanes in order, with labels and NO badges (regression)', () => {
  // Given a board whose team config was never read (null → defaults)
  const { mod, tab } = fresh({ config: null });
  // When the board renders
  mod.renderTasksBoard(tab);
  // Then exactly the five system lanes (in canonical order) plus the trailing
  // hidden `unknown` catch-all render — behaviourally identical to today.
  assert.deepEqual(laneStatuses(tab),
    ['todo', 'defining', 'in-progress', 'testing', 'done', 'unknown']);
  // And each visible system lane header carries today's label.
  const labels = {
    todo: 'To Do', defining: 'Defining', 'in-progress': 'In Progress',
    testing: 'Testing', done: 'Done',
  };
  for (const [status, label] of Object.entries(labels)) {
    const labelEl = findByClass(lane(tab, status), 'tasks-lane-label');
    assert.equal(labelEl.textContent, label, `${status} lane label`);
  }
  // And there are NO agent badges anywhere (REGRESSION: assert explicitly).
  assert.equal(findAllByClass(tab.els.tasksBoard, 'tasks-lane-agent').length, 0,
    'no-config board renders zero agent badges');
  // And no lane is a user lane (system lanes only) — they keep their data-status
  // colors (driven by the .tasks-lane[data-status=...] rules), never .user-lane.
  assert.equal(findAllByClass(tab.els.tasksBoard, 'user-lane').length, 0,
    'no-config board has no .user-lane accent lanes');
  // And the CSS still carries each system data-status color rule (colors preserved).
  for (const status of Object.keys(labels)) {
    assert.match(CSS, new RegExp(`\\.tasks-lane\\[data-status="${status}"\\] \\.tasks-lane-header`),
      `${status} keeps its data-status color rule`);
  }
});

test('Scenario (regression): the six hardcoded .tasks-lane divs are gone from index.html', () => {
  // Given the shipped index.html (lanes are now JS-generated by renderTasksBoard)
  // Then no static tasks-lane / data-status columns remain in the markup, and the
  // board container is the single empty mount point the renderer fills.
  assert.ok(!/class="tasks-lane[^"]*"\s+data-status=/.test(HTML),
    'no static data-status lane columns remain in index.html');
  assert.match(HTML, /class="tasksBoard tasks-board[^"]*"><\/div>/,
    'the tasks-board is an empty container the renderer populates');
});

// ===========================================================================
// Scenario: User column renders as a lane
//   Given config inserts ux-review after testing
//   Then six lanes render in config order and ux-review tickets show there
// ===========================================================================
test('Scenario: a config inserting ux-review after testing renders six lanes in order', () => {
  // Given a config that inserts a ux-review user column between testing and
  // done, and a ticket whose status is ux-review.
  const config = {
    columns: [
      { status: 'todo' }, { status: 'defining' }, { status: 'in-progress' },
      { status: 'testing' },
      { status: 'ux-review', label: 'UX Review', description: 'design pass' },
      { status: 'done' },
    ],
  };
  const { mod, tab } = fresh({
    config,
    tickets: ticketsMap([{ fm: { id: 'TASK-9', title: 'polish', status: 'ux-review' } }]),
  });
  // When the board renders
  mod.renderTasksBoard(tab);
  // Then six lanes render in config order (then the trailing unknown lane).
  assert.deepEqual(laneStatuses(tab),
    ['todo', 'defining', 'in-progress', 'testing', 'ux-review', 'done', 'unknown']);
  // And ux-review sits in the 5th slot, right after testing.
  assert.equal(laneStatuses(tab)[4], 'ux-review');
  // And the ux-review ticket appears in the ux-review lane — NOT in unknown.
  const ux = lane(tab, 'ux-review');
  assert.deepEqual(cardStatuses(ux), ['ux-review'], 'the ux-review ticket lands in its own lane');
  assert.equal(findAllByClass(lane(tab, 'unknown'), 'task-card').length, 0,
    'the ux-review ticket is not routed to unknown');
  // And the user lane carries the .user-lane accent + its configured label/description.
  assert.ok(ux.classList.contains('user-lane'), 'ux-review is a .user-lane');
  const labelEl = findByClass(ux, 'tasks-lane-label');
  assert.equal(labelEl.textContent, 'UX Review');
  assert.equal(labelEl.title, 'design pass', 'description renders as the header title tooltip');
});

// ===========================================================================
// Scenario: failed-testing still folds (edge)
//   Given a failed-testing ticket
//   Then its card renders in the Testing lane with the red marker
// ===========================================================================
test('Scenario (edge): a failed-testing ticket folds into Testing with the red marker', () => {
  // Given a failed-testing ticket on a default (no-config) board.
  const { mod, tab } = fresh({
    tickets: ticketsMap([{ fm: { id: 'TASK-3', title: 'oops', status: 'failed-testing' } }]),
  });
  // When the board renders
  mod.renderTasksBoard(tab);
  // Then there is no failed-testing lane and the card lands in Testing.
  assert.ok(!lane(tab, 'failed-testing'), 'no dedicated failed-testing lane');
  const testing = lane(tab, 'testing');
  assert.deepEqual(findAllByClass(testing, 'task-card').map((c) => c.dataset.status), ['failed-testing'],
    'the failed-testing card folds into the Testing lane');
  // And the card shows the red "failed" marker dot.
  const dot = findByClass(testing, 'task-card-dot');
  assert.ok(dot, 'a marker dot is rendered');
  assert.equal(dot.className, 'task-card-dot failed');
  // And the CSS paints that class red.
  assert.match(CSS, /\.task-card-dot\.failed\s*\{[^}]*background:\s*#f14c4c/i);
  // And it is not marked unknown / dumped into todo.
  assert.equal(findAllByClass(lane(tab, 'unknown'), 'task-card').length, 0);
  assert.equal(findAllByClass(lane(tab, 'todo'), 'task-card').length, 0);
});

test('Scenario (edge): failed-testing still folds into Testing even with a user column present', () => {
  // Given a config with a ux-review user column AND a failed-testing ticket.
  const config = { columns: [{ status: 'testing' }, { status: 'ux-review' }] };
  const { mod, tab } = fresh({
    config,
    tickets: ticketsMap([
      { fm: { id: 'TASK-3', title: 'x', status: 'failed-testing' } },
      { fm: { id: 'TASK-4', title: 'y', status: 'ux-review' } },
    ]),
  });
  // When rendered, failed-testing still folds into Testing (config-aware routing
  // must not accidentally route it to a user lane or unknown).
  mod.renderTasksBoard(tab);
  assert.deepEqual(cardStatuses(lane(tab, 'testing')), ['failed-testing']);
  assert.deepEqual(cardStatuses(lane(tab, 'ux-review')), ['ux-review']);
});

// ===========================================================================
// Scenario: Corrupt config (FAILURE)
//   Given team-config.json holds invalid JSON
//   Then the board renders defaults, keeps polling, and nothing throws
// ===========================================================================
test('Scenario (failure): a corrupt team-config.json renders defaults and never throws', async () => {
  // Given a folder whose team-config.json holds invalid JSON.
  const folder = 'C:\\proj';
  const tasksDir = folder + '\\tasks';
  const cfgPath = tasksDir + '\\team-config.json';
  const agentsDir = folder + '\\.claude\\agents';
  const { window } = makeWindow({
    files: { [cfgPath]: '{ this is : not valid json ' },
    dirs: { [agentsDir]: [], [tasksDir]: [] },
  });
  const mod = loadLaneModule(window, makeDocument(), console);
  const tab = makeTab({ folder });

  // When the board polls (first-ever read → invalid JSON kept null → defaults),
  // nothing throws.
  await assert.doesNotReject(() => mod.pollTasksOnce(tab, true));
  // Then the last-good config stays null (defaults) ...
  assert.equal(tab.tasks.config, null, 'invalid JSON is not adopted; config stays at defaults');
  // ... and the board rendered exactly the five default lanes.
  assert.deepEqual(laneStatuses(tab),
    ['todo', 'defining', 'in-progress', 'testing', 'done', 'unknown']);
  // And polling keeps working: a SECOND poll (still corrupt) also does not throw
  // and still shows defaults — the poll loop is not wedged by the bad file.
  await assert.doesNotReject(() => mod.pollTasksOnce(tab, true));
  assert.equal(tab.tasks.config, null);
});

test('Scenario (failure): a config read failure MID-poll keeps the last good config', async () => {
  // Given a first poll that read a VALID config (last-good adopted).
  const folder = 'C:\\proj';
  const tasksDir = folder + '\\tasks';
  const cfgPath = tasksDir + '\\team-config.json';
  const agentsDir = folder + '\\.claude\\agents';
  const goodCfg = JSON.stringify({ columns: [{ status: 'ux-review', label: 'UX Review' }] });
  const { window, files } = makeWindow({
    files: { [cfgPath]: goodCfg },
    dirs: { [agentsDir]: [], [tasksDir]: [] },
  });
  const mod = loadLaneModule(window, makeDocument(), console);
  const tab = makeTab({ folder });
  await mod.pollTasksOnce(tab, true);
  assert.deepEqual(tab.tasks.config, { columns: [{ status: 'ux-review', label: 'UX Review' }] },
    'the valid config is adopted');
  const uxBefore = lane(tab, 'ux-review');
  assert.ok(uxBefore, 'the ux-review lane rendered from the good config');

  // When a later poll hits invalid JSON (a mid-rewrite / corrupt read).
  files.set(cfgPath, '{ half-written');
  await assert.doesNotReject(() => mod.pollTasksOnce(tab, true));
  // Then the last good config is kept (NOT dropped to defaults) — the ux-review
  // lane is still present after the failed read.
  assert.deepEqual(tab.tasks.config, { columns: [{ status: 'ux-review', label: 'UX Review' }] },
    'the corrupt mid-poll read keeps the last good config');
  assert.ok(lane(tab, 'ux-review'), 'the ux-review lane survives a corrupt mid-poll read');
});

// ===========================================================================
// Scenario: Missing badge agent (FAILURE)
//   Given a column assigned agent "ghost"
//   Then the lane badge renders in warning style and rendering completes
// ===========================================================================
test('Scenario (failure): a column naming a nonexistent agent renders the badge in warning style', () => {
  // Given a ux-review column assigned agent "ghost", and an agent set that does
  // NOT contain "ghost".
  const config = { columns: [{ status: 'ux-review', label: 'UX', agent: 'ghost' }] };
  const { mod, tab } = fresh({ config, agentNames: new Set(['ba', 'coder']) });
  // When the board renders (rendering must complete without throwing).
  assert.doesNotThrow(() => mod.renderTasksBoard(tab));
  // Then the lane badge is present, shows the agent name, and carries the warning
  // `.missing` style (no .claude/agents/ definition).
  const badge = findByClass(lane(tab, 'ux-review'), 'tasks-lane-agent');
  assert.ok(badge, 'the agent badge rendered');
  assert.equal(badge.textContent, 'ghost');
  assert.ok(badge.classList.contains('missing'), 'a nonexistent agent gets the .missing warning style');
  // And the CSS gives .missing a red warning treatment.
  assert.match(CSS, /\.tasks-lane-agent\.missing\s*\{[^}]*#f14c4c/i);
});

test('Scenario: a column naming a KNOWN agent renders the badge without the warning style', () => {
  // Given a ux-review column assigned agent "ba", and an agent set containing "ba".
  const config = { columns: [{ status: 'ux-review', label: 'UX', agent: 'ba' }] };
  const { mod, tab } = fresh({ config, agentNames: new Set(['ba', 'coder']) });
  // When rendered
  mod.renderTasksBoard(tab);
  // Then the badge is plain (no .missing warning) — display-only metadata.
  const badge = findByClass(lane(tab, 'ux-review'), 'tasks-lane-agent');
  assert.ok(badge && !badge.classList.contains('missing'), 'a known agent gets the plain badge');
  assert.equal(badge.textContent, 'ba');
});

// ===========================================================================
// Scenario (edge): an out-of-config status still routes to the hidden unknown lane
// ===========================================================================
test('Scenario (edge): an out-of-config status routes to the unknown lane, which unhides only when it holds a card', () => {
  const { mod, tab } = fresh({
    tickets: ticketsMap([
      { fm: { id: 'TASK-1', title: 'a', status: 'todo' } },
      { fm: { id: 'TASK-2', title: 'b', status: 'bogus' } },
    ]),
  });
  mod.renderTasksBoard(tab);
  const unknownLane = lane(tab, 'unknown');
  // The bogus ticket lands in unknown (not todo), and the lane is shown because it
  // holds a card.
  assert.deepEqual(cardStatuses(unknownLane), ['bogus']);
  assert.ok(!unknownLane.classList.contains('hidden'), 'unknown lane is visible while it holds a card');
  // The todo ticket keeps its own lane.
  assert.deepEqual(cardStatuses(lane(tab, 'todo')), ['todo']);
});

test('Scenario (edge): with no out-of-config tickets, the unknown lane stays hidden', () => {
  const { mod, tab } = fresh({
    tickets: ticketsMap([{ fm: { id: 'TASK-1', title: 'a', status: 'todo' } }]),
  });
  mod.renderTasksBoard(tab);
  assert.ok(lane(tab, 'unknown').classList.contains('hidden'),
    'the unknown lane is hidden when empty so the board is not cluttered');
});

// ===========================================================================
// Scenario: lane counts survive dynamic generation; no lane has an Add button
// (TASK-206 removed the post-processing lane and its dedicated "+" Add button
// entirely — no lane gains any special Add affordance).
// ===========================================================================
test('Scenario: generated lane count spans report per-lane totals', () => {
  const { mod, tab } = fresh({
    tickets: ticketsMap([
      { fm: { id: 'TASK-1', title: 'a', status: 'todo' } },
      { fm: { id: 'TASK-2', title: 'b', status: 'todo' } },
      { fm: { id: 'TASK-3', title: 'c', status: 'testing' } },
    ]),
  });
  mod.renderTasksBoard(tab);
  assert.equal(findByClass(lane(tab, 'todo'), 'tasks-lane-count').textContent, '2');
  assert.equal(findByClass(lane(tab, 'testing'), 'tasks-lane-count').textContent, '1');
  assert.equal(findByClass(lane(tab, 'done'), 'tasks-lane-count').textContent, '0');
});

test('Scenario: no lane renders a "+" Add button (TASK-206 removed the post-processing lane\'s Add affordance)', () => {
  const { mod, tab } = fresh({});
  mod.renderTasksBoard(tab);
  // No lane — system or user — has an add button anymore.
  assert.equal(findAllByClass(tab.els.tasksBoard, 'tasks-lane-add').length, 0,
    'zero Add buttons render on any lane');
  assert.ok(!lane(tab, 'post-processing'), 'the post-processing lane no longer exists at all');
});

// ===========================================================================
// Scenario (edge): a lane removed from config drops its cards into unknown next render
// ===========================================================================
test('Scenario (edge): a user lane removed from config sends its orphaned cards to unknown on the next render', () => {
  // Given a first render with a ux-review lane holding a ux-review ticket.
  const withUx = { columns: [{ status: 'ux-review' }] };
  const { mod, tab } = fresh({
    config: withUx,
    tickets: ticketsMap([{ fm: { id: 'TASK-9', title: 'p', status: 'ux-review' } }]),
  });
  mod.renderTasksBoard(tab);
  assert.deepEqual(cardStatuses(lane(tab, 'ux-review')), ['ux-review']);
  // When the ux-review column is removed from config and the board re-renders,
  // the now-orphaned ux-review ticket falls into the unknown lane (config-aware
  // routing no longer recognises the status).
  tab.tasks.config = null;
  mod.renderTasksBoard(tab);
  assert.ok(!lane(tab, 'ux-review'), 'the ux-review lane is gone after config removal');
  assert.deepEqual(cardStatuses(lane(tab, 'unknown')), ['ux-review'],
    'the orphaned card falls to unknown, not todo');
});
